[book]
title = "Markdown指南"
authors = ["zzy"]
description = "Markdown指南, 精通Markdown, Markdown教程, Markdown语法, Markdown实例, Markdown实践"
src = "src"
multilingual = true

[build]
build-dir = "docs"

[output.html]
theme = "src/theme"
# default-theme = "rust"
git_repository_url = "https://github.com/zzy/markdown-guide"
curly-quotes = true
mathjax-support = true

[output.html.playpen]
editable = true
copy-js = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
