[book]
title = "Markdown指南 - Markdown Guide"
authors = ["zzy"]
language = "zh"
description = "Markdown指南, markdown guide, 精通Markdown, Markdown教程, Markdown语法, Markdown实例, Markdown实践"
src = "src"
multilingual = true

[build]
build-dir = "docs"

[output.html]
theme = "theme"
git-repository-url = "https://github.com/zzy/markdown-guide"
# default-theme = "rust"
curly-quotes = true
mathjax-support = true

[output.html.playpen]
editable = true
copy-js = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
